import AppContainer from "@/components/common/AppContainer";
import Header from "@/components/common/Header";
import Facilities from "@/components/screens/protected/Facilities";
import { Metadata } from "next";
import { headers } from "next/headers";

export const metadata: Metadata = {
  title: "Kova | Facilities",
  description: "Generated by create next app",
};

export default async function Page() {
  const headersList = await headers();
  const accountId = headersList.get("x-account-id") as string;

  return (
    <div className="flex h-full flex-col">
      <Header
        items={[
          { title: "Dashboard", href: "/dashboard" },
          { title: "Facilities" },
        ]}
      />

      <AppContainer>
        <Facilities accountId={accountId} />
      </AppContainer>
    </div>
  );
}
