import AppContainer from "@/components/common/AppContainer";
import Header from "@/components/common/Header";
import CreateSpace from "@/components/screens/protected/CreateSpace";
import { Metadata } from "next";
import { headers } from "next/dist/server/request/headers";

export const metadata: Metadata = {
  title: "Kova | Create Spaces",
  description: "Generated by create next app",
};

export default async function page() {
  const headersList = await headers();
  const accountId = headersList.get("x-account-id") as string;

  return (
    <div className="flex h-full flex-col">
      <Header
        items={[
          { title: "Dashboard", href: "/dashboard" },
          { title: "Spaces", href: "/spaces" },
          { title: "Create" },
        ]}
      />

      <AppContainer>
        <CreateSpace accountId={accountId} />
      </AppContainer>
    </div>
  );
}
