import AppContainer from "@/components/common/AppContainer";
import Header from "@/components/common/Header";
import Customers from "@/components/screens/protected/Customers";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Kova | Customers",
  description: "Generated by create next app",
};

export default function Page() {
  return (
    <div className="flex h-full flex-col">
      <Header
        items={[
          { title: "Dashboard", href: "/dashboard" },
          { title: "Customers" },
        ]}
      />
      <div className="flex-1 overflow-auto" data-scroll-container>
        <AppContainer>
          <Customers />
        </AppContainer>
      </div>
    </div>
  );
}
