import AppContainer from "@/components/common/AppContainer";
import Header from "@/components/common/Header";
import Dashboard from "@/components/screens/protected/Dashboard";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Kova | Dashboard",
  description: "Generated by create next app",
};

export default function Page() {
  return (
    <div className="flex h-full flex-col">
      <Header items={[{ title: "Dashboard" }]} />
      <div className="flex-1 overflow-auto" data-scroll-container>
        <AppContainer>
          <Dashboard />
        </AppContainer>
      </div>
    </div>
  );
}
