import Dashboard from "@/components/screens/Dashboard";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Nocta | Dashboard",
  description: "Generated by create next app",
};

export default function Page() {
  return <Dashboard />;
}
