import Customers from "@/components/screens/Customers";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Nocta | Customers",
  description: "Generated by create next app",
};

export default function Page() {
  return <Customers />;
}
